import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";

const inter = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`{inter.className} bg-gray-400`}>{children}</body>
    </html>
  );
}
